/*EJERCICIO # 1*/

--PRODUCTOS Y FABRICANTES

-- Tabla FABRICANTE

CREATE TABLE Fabricante (
    codigoFabricante NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombreFabricante VARCHAR2(100) NOT NULL,
    PRIMARY KEY (codigoFabricante)
);


-- Tabla PRODUCTO

CREATE TABLE Producto(
    codigoProducto NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombreProducto VARCHAR2(100) NOT NULL,
    precioProducto NUMBER NOT NULL,
    codigoFabricante NUMBER NOT NULL,
    PRIMARY KEY (codigoProducto),
    CONSTRAINT FK_Producto_Fabricante FOREIGN KEY (codigoFabricante)
        REFERENCES Fabricante (codigoFabricante)
);

/* INGRESANDO DATOS A LAS TABLAS */
INSERT INTO fabricante VALUES(1, 'Asus');
INSERT INTO fabricante VALUES(2, 'Lenovo');
INSERT INTO fabricante VALUES(3, 'Hewlett-Packard');
INSERT INTO fabricante VALUES(4, 'Samsung');
INSERT INTO fabricante VALUES(5, 'Seagate');
INSERT INTO fabricante VALUES(6, 'Crucial');
INSERT INTO fabricante VALUES(7, 'Gigabyte');
INSERT INTO fabricante VALUES(8, 'Huawei');
INSERT INTO fabricante VALUES(9, 'Xiaomi');

INSERT INTO producto VALUES(1, 'Disco duro SATA3 1TB', 86.99, 5);
INSERT INTO producto VALUES(2, 'Memoria RAM DDR4 8GB', 120, 6);
INSERT INTO producto VALUES(3, 'Disco SSD 1 TB', 150.99, 4);
INSERT INTO producto VALUES(4, 'GeForce GTX 1050Ti', 185, 7);
INSERT INTO producto VALUES(5, 'GeForce GTX 1080 Xtreme', 755, 6);
INSERT INTO producto VALUES(6, 'Monitor 24 LED Full HD', 202, 1);
INSERT INTO producto VALUES(7, 'Monitor 27 LED Full HD', 245.99, 1);
INSERT INTO producto VALUES(8, 'Portátil Yoga 520', 559, 2);
INSERT INTO producto VALUES(9, 'Portátil Ideapd 320', 444, 2);
INSERT INTO producto VALUES(10, 'Impresora HP Deskjet 3720', 59.99, 3);
INSERT INTO producto VALUES(11, 'Impresora HP Laserjet Pro M26nw', 180, 3);


/* CONSULTAS */

-- 1. Lista el nombre de todos los productos que hay en la tabla producto.
SELECT P.nombreProducto 
    FROM Producto P;
    
-- 2. Lista los nombres y los precios de todos los productos de la tabla producto.
SELECT P.nombreProducto, P.precioProducto
    FROM Producto P;
    
-- 3. Lista todas las columnas de la tabla producto.
SELECT * FROM Producto;

-- 4. Lista el nombre de los productos, el precio en euros y el precio en dólares estadounidenses (USD).
SELECT P.nombreProducto, CONCAT('Q.',P.precioProducto) AS Quetzales ,
    CONCAT('USD.', (P.precioProducto * 7.76)) AS Dólares,
    CONCAT('€', (P.precioProducto * 8.05)) AS Euros
        FROM Producto P;
        
-- 5. Lista los nombres y los precios de todos los productos de la tabla producto, convirtiendo los nombres a mayúscula.
SELECT UPPER(P.nombreProducto) AS Producto, precioProducto
    FROM Producto P;
    
-- 6. Lista los nombres y los precios de todos los productos de la tabla producto, convirtiendo los nombres a minúscula.
SELECT LOWER(P.nombreProducto) AS Producto, precioProducto
    FROM Producto P;

-- 7. Lista el nombre de todos los fabricantes en una columna, y en otra columna obtenga 
    -- en mayúsculas los dos primeros caracteres del nombre del fabricante.
SELECT F.nombreFabricante, UPPER(SUBSTR(F.nombreFabricante, 1, 2)) AS Result
    FROM Fabricante F;
    
-- 9. Lista los nombres y los precios de todos los productos de la tabla producto, redondeando el valor del precio.
SELECT P.nombreProducto, ROUND(P.precioProducto) as REDONDEADO
    FROM Producto P;
    
-- 10. Lista los nombres y los precios de todos los productos de la tabla producto, truncando el valor del precio para mostrarlo sin ninguna cifra decimal.
SELECT P.nombreProducto, TRUNC(P.precioProducto, 0) as REDONDEADO
    FROM Producto P;

-- 11.  Lista el código de los fabricantes que tienen productos en la tabla producto.
SELECT F.codigoFabricante
    FROM Fabricante F
        INNER JOIN Producto P
            ON F.codigoFabricante = P.codigoFabricante;

-- 12.  Lista el código de los fabricantes que tienen productos 
    -- en la tabla producto, eliminando los códigos que aparecen repetidos.
SELECT DISTINCT F.codigoFabricante
    FROM Fabricante F
        INNER JOIN Producto P
            ON F.codigoFabricante = P.codigoFabricante;
            
-- 13. Lista los nombres de los fabricantes ordenados de forma ascendente.
SELECT F.nombreFabricante
    FROM Fabricante F
        ORDER BY F.nombreFabricante ASC;
        
-- 14. Lista los nombres de los fabricantes ordenados de forma descendente.
SELECT F.nombreFabricante
    FROM Fabricante F
        ORDER BY F.nombreFabricante DESC;
        
-- 15. Lista los nombres de los productos ordenados en primer lugar por el nombre 
    -- de forma ascendente y en segundo lugar por el precio de forma descendente.
SELECT P.nombreProducto
    FROM Producto P
        ORDER BY P.nombreProducto ASC, P.precioProducto DESC;
        
-- 16. Devuelve una lista con las 5 primeras filas de la tabla fabricante
SELECT * FROM Producto WHERE ROWNUM <= 5;

-- 17. Devuelve una lista con 2 filas a partir de la cuarta fila de 
    -- la tabla fabricante. La cuarta fila también se debe incluir en la respuesta.
SELECT * FROM Fabricante F 
    WHERE F.codigoFabricante BETWEEN 3 AND 4;
    
-- 18. Lista el nombre y el precio del producto más barato. (Utilice solamente las cláusulas ORDER BY y LIMIT)
SELECT * FROM
(
    SELECT P.nombreProducto, P.precioProducto
    FROM Producto P
        ORDER BY P.precioProducto ASC
)   WHERE ROWNUM = 1;

-- 19. Lista el nombre y el precio del producto más caro. (Utilice solamente las cláusulas ORDER BY y LIMIT)
SELECT * FROM
(
    SELECT P.nombreProducto, P.precioProducto
    FROM Producto P
        ORDER BY P.precioProducto DESC
)   WHERE ROWNUM = 1;

-- 20. Lista el nombre de todos los productos del fabricante cuyo código de fabricante es igual a 2.
SELECT P.nombreProducto
    FROM Producto P
        WHERE P.codigoFabricante = 2;

-- 21. Lista el nombre de los productos que tienen un precio menor o igual a 120€.
SELECT P.nombreProducto 
    FROM Producto P
        WHERE P.precioProducto <= 120;

-- 22. Lista el nombre de los productos que tienen un precio mayor o igual a 120€.
SELECT P.nombreProducto 
    FROM Producto P
        WHERE P.precioProducto >= 120;
        
-- 23. Lista el nombre de los productos que tienen un precio mayor o igual a 120€.
SELECT P.nombreProducto 
    FROM Producto P
        WHERE NOT P.precioProducto >= 400;
        
-- 24. Lista todos los productos que tengan un precio entre 80€ y 300€. Sin utilizar el operador BETWEEN.
SELECT * FROM Producto P
    WHERE P.precioProducto >= 80
        AND P.precioProducto <= 300;

-- 25. Lista todos los productos que tengan un precio entre 60€ y 200€. Utilizando el operador BETWEEN.
SELECT * FROM Producto P
    WHERE P.precioProducto 
        BETWEEN 60 AND 200; 
        
-- 26. Lista todos los productos que tengan un precio mayor que 200€ y que el código de fabricante sea igual a 6.
SELECT * FROM  Producto P
    WHERE P.precioProducto > 200
        AND P.codigoFabricante = 6;

-- 27. Lista todos los productos donde el código de fabricante sea 1, 3 o 5. Sin utilizar el operador IN.
SELECT * FROM Producto P 
    WHERE P.codigoFabricante = 1
        OR P.codigoFabricante = 3
        OR P.codigoFabricante = 5;
        
-- 28. Lista todos los productos donde el código de fabricante sea 1, 3 o 5. Utilizando el operador IN.
SELECT * FROM Producto P
    WHERE P.codigoFabricante IN(1,3,5);

-- 29. Lista el nombre y el precio de los productos en céntimos (Habrá que multiplicar por 100 el valor 
    -- del precio). Cree un alias para la columna que contiene el precio que se llame céntimos.
SELECT P.nombreProducto, (P.precioProducto * 100) AS Céntimos
    FROM Producto P;
    
-- 30. Lista los nombres de los fabricantes cuyo nombre empiece por la letra S.
SELECT F.nombreFabricante 
    FROM Fabricante F
        WHERE F.nombreFabricante LIKE 'S%';
    
-- 31. Lista los nombres de los fabricantes cuyo nombre termine por la vocal e.
SELECT F.nombreFabricante 
    FROM Fabricante F
        WHERE F.nombreFabricante LIKE '%e';
        
-- 32. Lista los nombres de los fabricantes cuyo nombre contenga el carácter w.
SELECT F.nombreFabricante 
    FROM Fabricante F
        WHERE F.nombreFabricante LIKE '%w%';
        
-- 33. Lista los nombres de los fabricantes cuyo nombre sea de 4 caracteres.
SELECT F.nombreFabricante
    FROM Fabricante F
        WHERE F.nombreFabricante LIKE '____';

-- 34. Devuelve una lista con el nombre de todos los productos que contienen la cadena Portátil en el nombre.
SELECT P.nombreProducto
    FROM Producto P
        WHERE P.nombreProducto LIKE '%Portátil%';
        
-- 35. Devuelve una lista con el nombre de todos los productos que contienen la cadena Monitor en el nombre 
    -- y tienen un precio inferior a 215 €.
SELECT P.nombreProducto
    FROM Producto P
        WHERE P.nombreProducto LIKE '%Monitor%'
            AND P.precioProducto < 215;
            
-- 36. Lista el nombre y el precio de todos los productos que tengan un precio mayor o igual a 180€. 
    -- Ordene el resultado en primer lugar por el precio (en orden descendente) y en segundo lugar 
        --- por el nombre (en orden ascendente).










